#ifndef _CONFIG_H_
#define _CONFIG_H_

//#define	FOR_FC2
//#define	FOR_TMC
//#define	KATAOKA_LOGIC

#define	USE_CALC_PROCLINE
#define	NOT_USE_DISPARITY
//#define	FORCE_UseDisparity
//#define	NOT_USE_ADJUST_EDGE_THRESHOLD
#define	NOT_USE_FARAREA
//#define	SIMPLE_CALC_EDGE_STRENGTH
//#define	NOT_USE_selectLaneMarkerAtComplexLaneBoundary
//#define	USE_checkMismatchOfLaneMarkerPointsFromLaneParameter
//#define	USE_BB_DIFF
#define	USE_NON_DISPARITY_EDGEPOINT
//#define	NOT_USE_CONSTRANT_OF_GAP_BETWEEN_EDGE_POINT
#define	NOT_USE_GRIDMAP1D

//#define	FOR_WTP
/////////////////////////////////////////////////////////////////////////////////
#define	NOT_USE_TMC_STEREO_BMP
//#define	USE_TYTLABS_STEREO_AVI
//#define	FOR_DEMONSTRATION1
//#define	FOR_DEMONSTRATION2
//#define	LONG_FOCAL_LENGTH

//#define	FOR_TME
//#define	WINDOWS_DEBUG_MODE
//#define	NOT_USE_ROAD_WINDOW
//#define	NOT_USE_CONTROL_WINDOW
#define	NOT_USE_CONSOLE
#define	NOT_USE_LISTWINDOW

//#define	OVERLAY_ROADIMAGE_ON_INPUTIMAGE
//#define	USE_DYNAMIC_SYSTEM_NOISE
#define	PROCESS_PRIORITY	5

#define	SCALE_TO_DRAW_POINT	1

//#define	LONG_FOCAL_LENGTH

#define	SAFE_DELETE(p)	{	if(p != NULL)	{	delete p;	p = NULL;	}	}
#define	SAFE_DELETE_ARRAY(p)	{	if(p != NULL)	{	delete [] p;	p = NULL;	}	}

#define	GM_MOVINGAVERAGE_NUMBER	10
#define	GM_MOVINGAVERAGE_INVALID_VALUE	(1000000)


#define	ACC_FAC		100
#define	NO_STEER_SIGNAL
#define FIND_WIDE_LANE

#ifndef	M_PI
#define	M_PI	(3.141592)
#endif


//yuhuan 10.19
//#define	DB_REAL_FILTER_LENGTH	(80)
#define	DB_REAL_FILTER_LENGTH	(80)    //边沿检测滤波长度

// 边缘梯度能量阈值
#if	defined(FOR_DEMONSTRATION1) || defined(FOR_DEMONSTRATION2)
#define	CS4_POSITIVETHRESHOLD	(S4)64
#define	CS4_NEGATIVETHRESHOLD	(S4)(-(CS4_POSITIVETHRESHOLD))	// upper boundary of down edge strength
#elif	defined(FOR_TME)
#define	CS4_POSITIVETHRESHOLD	(S4)64
#define	CS4_NEGATIVETHRESHOLD	(S4)(-(CS4_POSITIVETHRESHOLD))	// upper boundary of down edge strength
#else	FOR_DEMONSTRATION
#define	CS4_POSITIVETHRESHOLD	(S4)16
#define	CS4_NEGATIVETHRESHOLD	(S4)(-(CS4_POSITIVETHRESHOLD))
#endif	FOR_DEMONSTRATION

#define	CS4_NEAR_BASEY	7000
#define	CS4_NEARHEIGHT	10000	          //(CS4_NEAR_TOPY - CS4_NEAR_BASEY)
#define	CS4_NEAR_TOPY	(CS4_NEAR_BASEY + CS4_NEARHEIGHT)	//17000
#define	CS4_NEARIMAGEHEIGHT		100      //近处图像高度
#define	CS4_NEARWIDTH			50000    //实际道路横向宽度
#define	CS4_NEARIMAGEWIDTH		962      //近处图像宽度
//#define	CS4_NEAR_MAX_YAW	22//50
//#define	CS4_NEAR_MAX_YAW	44	// 20100831

#if	!defined(FOR_DEMONSTRATION2)
#define	CS4_NEAR_MAX_YAW	88	// 20111107
#else	!defined(FOR_DEMONSTRATION2)
#define	CS4_NEAR_MAX_YAW	44	// 20111107
#endif	!defined(FOR_DEMONSTRATION2)

#define	CS4_NUMBER_OF_NEAR_YAW		(CS4_NEAR_MAX_YAW * 2 + 1)
#define	CS4_NUMBER_OF_NEAR_OFFSET	CS4_NEARIMAGEWIDTH
#define	CS4_NUNBER_OF_NEAR_BALLOT	256

#define	CS4_FAR_BASEY	CS4_NEAR_TOPY	//17000
#define	CS4_FARHEIGHT	CS4_NEARHEIGHT	//10000	//(CS4_FAR_TOPY - CS4_FAR_BASEY)

#define	CS4_FAR_TOPY	(CS4_FAR_BASEY + CS4_FARHEIGHT)	//27000
#define	CS4_FARIMAGEHEIGHT		CS4_NEARIMAGEHEIGHT	//100
#define	CS4_FARWIDTH			CS4_NEARWIDTH	//10000
#define	CS4_FARIMAGEWIDTH		CS4_NEARIMAGEWIDTH	//192

#define	CS4_FARAREA_TOPY	80000
#define	CS4_WEIGHT_MAX	1

#define	CS4_MINIMUM_VOTES		(CS4_WEIGHT_MAX * 30)	// 20110630
#define	VOTING_THRESHOLD_RATIO	5

/////////////////////////////////
//#define	CS4_MAXIMUM_LINEWIDTH	500
#define	CS4_MAXIMUM_LINEWIDTH	1000	// 2011124
//TODO 100
#define	CS4_NEAR_MINIMUM_LINEWIDTH	80	// 20110704

#define	V_V_M	1
#define	FALSE	0
#define	TRUE	1

#define CS4_NOISE	1

#define	DB_OFFSET_MAX			(2000)
#define	DB_OFFSET_MIN			(-2000)
#define	DB_YAW_MAX			(45.0 / 180 * M_PI)
#define	DB_YAW_MIN			(-DB_YAW_MAX)
#define	DB_CURVATURE_MAX		(5e-5)
#define	DB_CURVATURE_MIN		(-5e-5)

#ifdef FIND_WIDE_LANE
#define	DB_LW_MAX			(8000)
#else FIND_WIDE_LANE
#define	DB_LW_MAX			(4000)
#endif FIND_WIDE_LANE

#define	DB_LW_MIN			(2000)

#define	DB_PITCH_MAX	(5.0 / 180. * M_PI)
#define	DB_PITCH_MIN	(-DB_PITCH_MAX)

#define	CDB_OFFSET_SCALE	(1.)
#define	CDB_YAW_SCALE		(1.)
#define	CDB_C_SCALE			(1.)
#define	CDB_LW_SCALE		(1.)
#define	CDB_DP_SCALE		(1.)

#define	CS4_LW_LSB	(1.)
#define	CS4_DP_LSB	(10000.)
#define	CS4_CURVATURE_LSB	(100000. * 1000)


// 20110928
#define	DEFAULT_SEARCH_MARGIN_IN_NEAR_AREA	(300.)
#define	DEFAULT_SEARCH_MARGIN_IN_FAR_AREA	(300.)
//#define	DEFAULT_MAX_DIFF_FROM_MEDIAN_DEVIATION_IN_NEAR_AREA (100.)
//#define	DEFAULT_MAX_DIFF_FROM_MEDIAN_DEVIATION_IN_NEAR_AREA (50.)	// 20111007
//#define	DEFAULT_MAX_DIFF_FROM_MEDIAN_DEVIATION_IN_FAR_AREA	(100.)
#define	DEFAULT_MAX_DIFF_FROM_MEDIAN_DEVIATION_IN_NEAR_AREA (50.)	// 20111121
#define	DEFAULT_MAX_DIFF_FROM_MEDIAN_DEVIATION_IN_FAR_AREA	(50.)	// 20111121

#define	DB_OFFSET_AVE		(0)
#define	DB_YAW_AVE			(0)
#define	DB_CURVATURE_AVE	(0)
#define	DB_LW_AVE			(3500)
#define	DB_DP_AVE			(0)

#define	CDB_SIGMA_PSI	(0.0)	// 20111026
#define	CDB_SIGMA_PSIDASH	(0.5 / 180 * M_PI)

#define	CDB_SIGMA_E			(0.0)// [mm]	// 20111026
#define	CDB_SIGMA_EDASH	(1.0 * 1000)	// [mm/s]

#define	CDB_SIGMA_RHO	(0.0)	// [1/mm]	// 20111026
//#define	CDB_SIGMA_RHODASH	(1.0e-6 * 1.0e-6)	// [1/mm^2]// 20111025
#define	CDB_SIGMA_RHODASH	(1.0e-5 * 1.0e-6)	// [1/mm^2]// 20111026

#define	CDB_SIGMA_DELTAPHI	(1.0 / 180 * M_PI)
#define	CDB_SIGMA_WIDTH	(1.0 * 1000)	// [mm]

// configuration
#define	MINIMUM_CV	(0.0001)
#define	MINIMUM_AVERAGE_EDGE_STRENGTH_RATIO	(0.5)
//#define	MAXMIMUM_DIFF_OF_ENDPOINT	(5000.)
#define	MAXMIMUM_DIFF_OF_ENDPOINT	(1000.)
//#define	MINIMUM_RATIO_OF_POINTNUM	(0.5)
//#define	MINIMUM_RATIO_OF_POINTNUM	(0.8)	// 20111121
#define	MINIMUM_RATIO_OF_POINTNUM	(0.7)
#define	MINIMUM_RATIO_OF_VOTES	(0.5)
#define	MINIMUM_FILTER_LENGTH	(2)
#define	MAXIMUM_YAW_OF_LANEMARKERLINESEQUENCE	(20)
//TODO 3. / 8
#define	MINIMUM_OFFSET_FOR_LANEMARKERLINESEQUENCE_INHIBIT	(4. / 8)
//TODO 6. / 8
#define	MAXIMUM_OFFSET_FOR_LANEMARKERLINESEQUENCE_INHIBIT	(5. / 8)
//TODO 50
#define	MAXIMUM_HORIZONTAL_DIFF_AT_REGION_BOUNDARY	(30.)
//TODO 5
#define	MAXIMUM_YAW_DIFF_AT_REGION_BOUNDARY	(50)
#define	OFFSETMARGIN_FOR_LANEMARKERLINE_3D	5
#define	SEARCH_MARGIN_FOR_LANEBOUNDARY	(500.)
///////#define	SEARCH_MARGIN_FOR_YAW	(20)

//#define	INSIDE_OF_LANEBOUNDARY_FOR_LANE_BOUNDARY	(1000.)	//(500.)	//20111103(枹巊梡)
#define	OUTSIDE_OF_LANEBOUNDARY_FOR_LANE_BOUNDARY	(1500.)
//#define	MARGIN_OFFSET_FOR_LANE_BOUNDARY_TRACKING	(500.)
//TODO 250
#define	MARGIN_FOR_SEARCH_LANEMARKER_WITH_INITIAL_PARAMETER	(200.)

//#define	MAXIMIM_YAW_DIFF_AT_REGION_BOUNDARY	(10)

#define OFFSET_SEARCH_MARGIN_SEQUENCE	(200.)				// 嬤朤幵慄嫬奅偲墦曽幵慄嫬奅偺椞堟嫬奅偱偺偢傟偺嫋梕抣	// 20110703
#define YAW_SEARCH_MARGIN_SEQUENCE	(3.0 / 180. * M_PI)				// 嬤朤幵慄嫬奅偲墦曽幵慄嫬奅偺椞堟嫬奅偱偺偢傟偺嫋梕抣	// 20110703
//#define OFFSET_SEARCH_MARGIN_TRACK	(1000.)				// 嬤朤幵慄嫬奅偲墦曽幵慄嫬奅偺椞堟嫬奅偱偺偢傟偺嫋梕抣	// 20110703
#define OFFSET_SEARCH_MARGIN_TRACK	(200.)				// 嬤朤幵慄嫬奅偲墦曽幵慄嫬奅偺椞堟嫬奅偱偺偢傟偺嫋梕抣	// 20111129
#define YAW_SEARCH_MARGIN_TRACK	(1.0 / 180. * M_PI)				// 嬤朤幵慄嫬奅偲墦曽幵慄嫬奅偺椞堟嫬奅偱偺偢傟偺嫋梕抣	// 20110703

//#define	MAXIMUM_DIFF_FROM_PREVIOUS_FOUND_I	(10)	// 婛専弌揰偲偺悅捈曽岦偺嵟戝僊儍僢僾(巄掕)
//#define	MAXIMUM_DIFF_FROM_PREVIOUS_FOUND_J	(10)	// 婛専弌揰偲偺悈暯曽岦偺嵟戝僊儍僢僾(巄掕)
#define	MAXIMUM_DIFF_FROM_PREVIOUS_FOUND_I	(100)	// 婛専弌揰偲偺悅捈曽岦偺嵟戝僊儍僢僾(巄掕)// 20120416
#define	MAXIMUM_DIFF_FROM_PREVIOUS_FOUND_J	(100)	// 婛専弌揰偲偺悈暯曽岦偺嵟戝僊儍僢僾(巄掕)// 20120416

#define	MAXIMUM_DIFF_FROM_PREVIOUS_FOUND_Z	(15.0 * 1000)	// 20111121// 婛専弌揰偲偺倅曽岦偺嵟戝僊儍僢僾(巄掕)
#define	MAXIMUM_DIFF_FROM_PREVIOUS_FOUND_X	(0.5 * 1000)	// 20120118// 婛専弌揰偲偺倃曽岦偺嵟戝僊儍僢僾(巄掕)
//#define	MAXIMUM_DIFF_FROM_PREVIOUS_FOUND_X	(2.0 * 1000)	// 20120124

////#define	DB_OFFSET_MARGIN_OUTSIDE	OUTSIDE_OF_LANEBOUNDARY_FOR_LANE_BOUNDARY	// 20111103//枹巊梡
////#define	DB_OFFSET_MARGIN_INSIDE		INSIDE_OF_LANEBOUNDARY_FOR_LANE_BOUNDARY	// 20111103//枹巊梡


#define	MAX_DISTANCE_OF_FIRST_DETECTED_POINT	(50000.)	// 墦曽敀慄揰扵嶕帪偵巒傔偰尒偮偐偭偨揰偺嵟彫嫋梕嫍棧(墦偡偓傞揰偰弶傔偰尒偮偐偭偨応崌偼拞巭)
#define	MAXIMUM_RATIO_OF_REJECTED_POINTS	(0.5)	// 攋婞偝傟偨幵慄嫬奅揰偺妱崌偺嵟戝抣(巄掕)


#define	MINIMUM_SEARCHMARGIN_IN_PIXEL	10	// 悇掕埵抲傪拞怱偲偡傞扵嶕斖埻偺嵟彫暆[pix]	// 20111109


//#define	EDGETHRESHOLD_FACTOR_FOR_LANEMARKER	6
//#define	EDGETHRESHOLD_FACTOR_FOR_LANEMARKER	8	// 20111103
//#define	EDGETHRESHOLD_FACTOR_FOR_LANEMARKER	6	// 20111107
//#define	EDGETHRESHOLD_FACTOR_FOR_LANEMARKER	2	// 20111109
#define	EDGETHRESHOLD_FACTOR_FOR_LANEMARKER	1	// 20111124	// 敀慄岓曗専弌帪偼丆暯嬒僄僢僕嫮搙偺鑷抣傪僄僢僕揰専弌帪偺鑷抣傛傝崅傔偵愝掕偡傞
#define	CURB_MARGIN	300	//[mm]	// 棫懱幵慄嫬奅扵嶕斖埻偺幵慄嫬奅敀慄偐傜偺嫍棧[mm]
#define	EDGESTRENGTH_RATIO_TO_ELIMINATE	0.5	// 20110921// 暯嬒僄僢僕嫮搙偲斾妑偟庛偄僄僢僕揰傪嶍彍
#define	MAX_SECOND_VALUE	(400.)	// 枹巊梡

#define	LANE_BOUNDARY_POINTS_NUMBER_FOR_PARAMETER_ESTIMATION	10	// 僷儔儊乕僞悇掕偵梡偄傞幵慄嫬奅揰悢
#define	MINIMUM_RATIO_OF_EDGESTRENGTH_FOR_FARAREA_LANEBOUNDARY	0.5	// 墦曽敀慄揰扵嶕帪偵嫋梕偡傞嬤朤敀慄揰偺暯嬒僄僢僕嫮搙偲偺斾



#ifndef	FOR_TME
#define	COUNT_FOR_FOUND_STATUS_LANE_SIDE	5	// 敪尒仺捛愓堏峴僼儗乕儉悢(嵍塃)
#define	COUNT_FOR_LOST_STATUS_LANE_SIDE		3	// 捛愓仺敪尒堏峴僼儗乕儉悢(嵍塃)
//#define	COUNT_FOR_LOST_STATUS_LANE_SIDE		10	// 捛愓仺敪尒堏峴僼儗乕儉悢(嵍塃)	20111003
#define	COUNT_FOR_FOUND_STATUS_LANE_REGION	5	// 敪尒仺捛愓堏峴僼儗乕儉悢(嬤墦)
#define	COUNT_FOR_LOST_STATUS_LANE_REGION	3	// 捛愓仺敪尒堏峴僼儗乕儉悢(嬤墦)
//#define	COUNT_FOR_LOST_STATUS_LANE_REGION	10	// 捛愓仺敪尒堏峴僼儗乕儉悢(嬤墦)	20111003
#define	LBT_LANEMARKER_FOUND_COUNT	3	// 敀慄敪尒仺捛愓堏峴僼儗乕儉悢
#define	LBT_LANEMARKERLINE_FOUND_COUNT	3// 僄僢僕慄敪尒仺捛愓堏峴僼儗乕儉悢
//#define	LBT_LANEMARKERLINE_FOUND_COUNT	5	// 20111003
#define	LBT_LANEMARKER_LOST_COUNT	3	// 敀慄捛愓仺枹専弌堏峴僼儗乕儉悢
#define	LBT_LANEMARKERLINE_LOST_COUNT	3	// 僄僢僕慄捛愓仺枹専弌堏峴僼儗乕儉悢
//#define	LBT_LANEMARKERLINE_LOST_COUNT	5	// 20111003
#else	FOR_TME
#define	COUNT_FOR_FOUND_STATUS_LANE_SIDE	5	// 敪尒仺捛愓堏峴僼儗乕儉悢(嵍塃)
#define	COUNT_FOR_LOST_STATUS_LANE_SIDE		10	// 捛愓仺敪尒堏峴僼儗乕儉悢(嵍塃)	20111003
#define	COUNT_FOR_FOUND_STATUS_LANE_REGION	5	// 敪尒仺捛愓堏峴僼儗乕儉悢(嬤墦)
#define	COUNT_FOR_LOST_STATUS_LANE_REGION	10	// 捛愓仺敪尒堏峴僼儗乕儉悢(嬤墦)	20111003
#define	LBT_LANEMARKER_FOUND_COUNT	3
#define	LBT_LANEMARKERLINE_FOUND_COUNT	3
#define	LBT_LANEMARKER_LOST_COUNT	10
#define	LBT_LANEMARKERLINE_LOST_COUNT	10
#endif	FOR_TME




#define	COUNT_FOR_SOLID_LINE	2	// 幚慄専弌敾掕僼儗乕儉悢
#define	COUNT_FOR_DASH_LINE	2	// 攋慄専弌敾掕僼儗乕儉悢
//#define	COUNT_FOR_DASH_LINE	10	// 攋慄専弌敾掕僼儗乕儉悢	20111107
#define	MIN_RATIO_OF_SOLID_LINE_FOR_ONELINE_FILTER	(0.7)	// 20120127	// 幚慄偲傒側偡堊偺張棟儔僀儞悢偵懳偡傞幵慄嫬奅揰悢偺斾偺嵟彫抣
// TODO 0.25
#define	AVERAGE_EDGE_STRENGTH_AND_TH_RATIO	(0.8)	// 暯嬒僄僢僕嫮搙偵傛傞摦揑鑷抣愝掕帪偺僷儔儊乕僞

//#define	MISMATCH_OF_LANEMARKERPOINTS_FROM_LANEPARAMATER_PIXEL	(10)	// 幵慄嫬奅揰偲憱楬僷儔儊乕僞偵傛傞幵慄嫬奅偲偺偢傟偺嫋梕暆[pix]
#define	MISMATCH_OF_LANEMARKERPOINTS_FROM_LANEPARAMATER_PIXEL	(20)	// 幵慄嫬奅揰偲憱楬僷儔儊乕僞偵傛傞幵慄嫬奅偲偺偢傟偺嫋梕暆[pix]	// 20111201
#define	MISMATCH_OF_LANEMARKERPOINTS_FROM_LANEPARAMETER_RATIO	(0.5)	// 幵慄嫬奅揰偲憱楬僷儔儊乕僞偵傛傞幵慄嫬奅偲偺偢傟検偺斾偺嫋梕検

/// V moved at 20120313 ///////////////////////////////
#define	EXTENDED_HEIGHT_FOR_FAR_AREA	20	// 屌掕僺僢僠妏偱嶼弌偝傟傞墦曽椞堟偺嵟墦儔僀儞傪夋憸忋曽傊偢傜偟丆墦曽椞堟傪奼戝偡傞

#define	FACTOR_OF_LANEMARKER_WIDTH_FOR_FARSIDE	2	// 敀慄岓曗偺墦曽懁敀慄暆偺惂栺偺娚榓學悢

#define	FACTOR_FOR_AVERAGE_INTENSITY_OF_LANEMARKER	2	// 暯嬒婸搙偵娭偡傞敀慄忦審偺學悢

#define	LANEMARKERPAIR_MINIMUM_WIDTH	(2500.)	// 敀慄儁傾帪偺嫋梕嵟彫娫妘
#define	LANEMARKERPAIR_MAXIMUM_WIDTH	(5000.)	// 敀慄儁傾帪偺嫋梕嵟戝娫妘
//#define	LANEMARKERPAIR_MAXIMUM_YAWDIFF_DEG	(10.)	// 敀慄儁傾帪偺嫋梕嵟戝儓乕偢傟(屌掕僺僢僠妏)//10
#define	LANEMARKERPAIR_MAXIMUM_YAWDIFF_DEG	(4.)//2014.9.25

//#define	MULTIDIRECTION_CALCEDGESTRENGTH		// 巜掕曽岦(0,45,-45搙)偺僄僢僕嫮搙傪嶼弌

#define	FACTOR_FOR_FAR_END_OF_PROCLINE	1 / 5	// 夋憸忋晹偺僄僢僕揰専弌枹張棟椞堟

#define	INVALID_DISTANCE_VALUE	(100. * 1000)	// 柍岠側嫍棧偺抣[mm]

//#define	MAXIMUM_YAW_DIFF_IN_COMPLEX_LANE_MARKER	(5)
#define	MAXIMUM_YAW_DIFF_IN_COMPLEX_LANE_MARKER	(10)	// 20111124	// 暋崌慄偺暯峴慄孮偲傒側偡堊偺儓乕妏偺嵎偺嵟戝抣[pix]
#define	MAXIMUM_OFFSET_DIFF_IN_COMPLEX_LANE_MARKER	(10)// 暋崌慄偺暯峴慄孮偲傒側偡堊偺僆僼僙僢僩偺嵎偺嵟戝抣[pix]
#define	MINIMUM_OFFSET_DIFF_IN_COMPLEX_LANE_MARKER	(-3)// 暋崌慄偺暯峴慄孮偲傒側偡堊偺僆僼僙僢僩偺嵎偺嵟彫抣[pix]

#define	MINIMUM_POINT_NUMBER_FOR_LANEMARKER_TYPE	10

#define	MAXIMUM_LINE_SEGMENT_FOR_LANEMARKER_TYPE	10

#define	MAXIMUM_GAP_OF_LINE_SEGMENT_FOR_LANEMARKER_TYPE	20


#define	MAXIMUMLINE_SEGMENT_OF_DASH_LANEBOUNDARY_TYPE	2	// 攋慄偲傒側偡偨傔偺嵟戝慄暘悢

// 暋崌慄儌乕僪偺忬懺慗堏梡僇僂儞僞偺鑷抣
#define	FRAME_CLBT_SINGLE_TO_NONE	10//5	//暋崌慄儌乕僪偺扨弮慄仺枹専弌忬懺慗堏偺偨傔偺僼儗乕儉悢
#define	FRAME_CLBT_DOUBLE_TO_NONE	10//5	//暋崌慄儌乕僪偺擇廳慄仺枹専弌忬懺慗堏偺偨傔偺僼儗乕儉悢
#define	FRAME_CLBT_DOUBLE_TO_SINGLE	10//5	//暋崌慄儌乕僪偺擇廳慄仺扨弮慄忬懺慗堏偺偨傔偺僼儗乕儉悢
#define	FRAME_CLBT_TRIPLE_TO_NONE	10//5	//暋崌慄儌乕僪偺嶰廳慄仺枹専弌忬懺慗堏偺偨傔偺僼儗乕儉悢
#define	FRAME_CLBT_TRIPLE_TO_SINGLE	10//5	//暋崌慄儌乕僪偺嶰廳慄仺扨弮慄忬懺慗堏偺偨傔偺僼儗乕儉悢
#define	FRAME_CLBT_TRIPLE_TO_DOUBLE	10//5	//暋崌慄儌乕僪偺嶰廳慄仺擇廳慄忬懺慗堏偺偨傔偺僼儗乕儉悢

#define	GAP_IN_COMPLEX_LANE_BOUNDARY	2000.	// 枹巊梡

#define	MININUM_POINT_NUMBER_FOR_NEAR_AREA	10	// 憱楬僷儔儊乕僞偵傛傞嬤朤椞堟偺幵慄嫬奅揰扵嶕帪偺嵟彮揰悢
#define	MAXIMUM_GAP_BETWEEN_CONNECTED_POINTS	3

#define	BOTHSIDE_LOST_COUNT	10

#define	FACTOR_FOR_SEARCHING_IN_DEFAULT_LANE_POSITION	2


#define	MAXIMUM_YAW_FOR_MAIN_LANE	(1.0 / 180 * M_PI)
#define	MINIMUM_YAW_FOR_BRANCH_LANE	(5.0 / 180 * M_PI)

#define	CALC3DPLANE_MAXIMUM_A	0.5

#define	MAXIMUM_AVERAGE_DISTANCE_FROM_3D_SURFACE	100.
#define	MAXINUM_GAP_FOR_ISOLATED_LANE_BOUNDARY	(15000.)

#define	MAXIMUM_ISRC_DIFF_FOR_ISOLATED_LANE_BOUNDARY_POINTS	(5)
#define	MAXIMUM_JSRC_DIFF_FOR_ISOLATED_LANE_BOUNDARY_POINTS	(5)

#define	SEARCH_MARGIN_IN_NEAR_AREA	(500.)
#define	SEARCH_MARGIN_IN_FAR_AREA	(500.)

//#define	DB_OFFSET_MIN_FACTOR	1
//#define	DB_OFFSET_MIN_FACTOR	10	//20111122
#define	DB_OFFSET_MIN_FACTOR	5
#define	OBSERVER_ERROR_FACTOR	1.0
#define	MINIMUM_VELOCITY (30. * 1000 / 3600. * 1000)

#define	MINIMUM_Z3D	(1.0 * 1000)
//#define	TH_ABOVE_GROUND	100.0
#define	TH_ABOVE_GROUND	150.0

#define	LENGTH_TO_ELIMINATE_SHORT_LANEMARKERLINES	(2000.)
#define	LENGTH_TO_ELIMINATE_FEWPOINT_LANEMARKERLINES	(20)


#endif _CONFIG_H_
