/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <lcm/lcm_coretypes.h>

#ifndef __nad_lcm_oc_vui_report_hpp__
#define __nad_lcm_oc_vui_report_hpp__

#include <vector>
#include "nad_lcm/obu_info.hpp"
#include "nad_lcm/rsu_info.hpp"
#include "nad_lcm/key_point_info.hpp"
#include "nad_lcm/route_line_point.hpp"
#include "nad_lcm/light_info.hpp"
#include "nad_lcm/limspeed_info.hpp"
#include "nad_lcm/block_info.hpp"
#include "nad_lcm/obstacle_info.hpp"
#include "nad_lcm/platoon_info.hpp"
#include "nad_lcm/co_obu_info.hpp"
#include "nad_lcm/ne_info.hpp"
#include "nad_lcm/qos_info.hpp"
#include "nad_lcm/route_planning.hpp"

namespace nad_lcm
{

class oc_vui_report
{
    public:
        nad_lcm::obu_info obu;

        double     sug_speed;

        int32_t    right_of_way;

        nad_lcm::rsu_info rsu;

        double     rsu_lon;

        double     rsu_lat;

        int16_t    num_of_key;

        std::vector< nad_lcm::key_point_info > key_point;

        int16_t    cur_point_index;

        int16_t    num_of_point;

        std::vector< nad_lcm::route_line_point > line;

        int16_t    num_of_light;

        std::vector< nad_lcm::light_info > light;

        int16_t    num_of_limspeed;

        std::vector< nad_lcm::limspeed_info > limspeed;

        int16_t    num_of_block;

        std::vector< nad_lcm::block_info > block;

        int16_t    num_of_obstacle;

        std::vector< nad_lcm::obstacle_info > obstacle;

        int16_t    num_of_platoon;

        std::vector< nad_lcm::platoon_info > platoon;

        int16_t    num_of_co_obu;

        std::vector< nad_lcm::co_obu_info > co_obu;

        int16_t    num_of_ne;

        std::vector< nad_lcm::ne_info > ne;

        nad_lcm::qos_info qos;

        nad_lcm::route_planning route;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to reqad while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "oc_vui_report"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int oc_vui_report::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = (int64_t)getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int oc_vui_report::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int oc_vui_report::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t oc_vui_report::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* oc_vui_report::getTypeName()
{
    return "oc_vui_report";
}

int oc_vui_report::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = this->obu._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->sug_speed, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->right_of_way, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->rsu._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->rsu_lon, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->rsu_lat, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &this->num_of_key, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->num_of_key; a0++) {
        tlen = this->key_point[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &this->cur_point_index, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &this->num_of_point, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->num_of_point; a0++) {
        tlen = this->line[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &this->num_of_light, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->num_of_light; a0++) {
        tlen = this->light[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &this->num_of_limspeed, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->num_of_limspeed; a0++) {
        tlen = this->limspeed[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &this->num_of_block, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->num_of_block; a0++) {
        tlen = this->block[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &this->num_of_obstacle, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->num_of_obstacle; a0++) {
        tlen = this->obstacle[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &this->num_of_platoon, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->num_of_platoon; a0++) {
        tlen = this->platoon[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &this->num_of_co_obu, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->num_of_co_obu; a0++) {
        tlen = this->co_obu[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &this->num_of_ne, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->num_of_ne; a0++) {
        tlen = this->ne[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = this->qos._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->route._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int oc_vui_report::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = this->obu._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->sug_speed, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->right_of_way, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->rsu._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->rsu_lon, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->rsu_lat, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &this->num_of_key, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    this->key_point.resize(this->num_of_key);
    for (int a0 = 0; a0 < this->num_of_key; a0++) {
        tlen = this->key_point[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &this->cur_point_index, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &this->num_of_point, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    this->line.resize(this->num_of_point);
    for (int a0 = 0; a0 < this->num_of_point; a0++) {
        tlen = this->line[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &this->num_of_light, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    this->light.resize(this->num_of_light);
    for (int a0 = 0; a0 < this->num_of_light; a0++) {
        tlen = this->light[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &this->num_of_limspeed, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    this->limspeed.resize(this->num_of_limspeed);
    for (int a0 = 0; a0 < this->num_of_limspeed; a0++) {
        tlen = this->limspeed[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &this->num_of_block, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    this->block.resize(this->num_of_block);
    for (int a0 = 0; a0 < this->num_of_block; a0++) {
        tlen = this->block[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &this->num_of_obstacle, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    this->obstacle.resize(this->num_of_obstacle);
    for (int a0 = 0; a0 < this->num_of_obstacle; a0++) {
        tlen = this->obstacle[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &this->num_of_platoon, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    this->platoon.resize(this->num_of_platoon);
    for (int a0 = 0; a0 < this->num_of_platoon; a0++) {
        tlen = this->platoon[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &this->num_of_co_obu, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    this->co_obu.resize(this->num_of_co_obu);
    for (int a0 = 0; a0 < this->num_of_co_obu; a0++) {
        tlen = this->co_obu[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &this->num_of_ne, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    this->ne.resize(this->num_of_ne);
    for (int a0 = 0; a0 < this->num_of_ne; a0++) {
        tlen = this->ne[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = this->qos._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->route._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int oc_vui_report::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += this->obu._getEncodedSizeNoHash();
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += this->rsu._getEncodedSizeNoHash();
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __int16_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->num_of_key; a0++) {
        enc_size += this->key_point[a0]._getEncodedSizeNoHash();
    }
    enc_size += __int16_t_encoded_array_size(NULL, 1);
    enc_size += __int16_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->num_of_point; a0++) {
        enc_size += this->line[a0]._getEncodedSizeNoHash();
    }
    enc_size += __int16_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->num_of_light; a0++) {
        enc_size += this->light[a0]._getEncodedSizeNoHash();
    }
    enc_size += __int16_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->num_of_limspeed; a0++) {
        enc_size += this->limspeed[a0]._getEncodedSizeNoHash();
    }
    enc_size += __int16_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->num_of_block; a0++) {
        enc_size += this->block[a0]._getEncodedSizeNoHash();
    }
    enc_size += __int16_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->num_of_obstacle; a0++) {
        enc_size += this->obstacle[a0]._getEncodedSizeNoHash();
    }
    enc_size += __int16_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->num_of_platoon; a0++) {
        enc_size += this->platoon[a0]._getEncodedSizeNoHash();
    }
    enc_size += __int16_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->num_of_co_obu; a0++) {
        enc_size += this->co_obu[a0]._getEncodedSizeNoHash();
    }
    enc_size += __int16_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->num_of_ne; a0++) {
        enc_size += this->ne[a0]._getEncodedSizeNoHash();
    }
    enc_size += this->qos._getEncodedSizeNoHash();
    enc_size += this->route._getEncodedSizeNoHash();
    return enc_size;
}

uint64_t oc_vui_report::_computeHash(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == oc_vui_report::getHash)
            return 0;
    const __lcm_hash_ptr cp = { p, (void*)oc_vui_report::getHash };

    uint64_t hash = 0xe0be486eb2cf0d8cLL +
         nad_lcm::obu_info::_computeHash(&cp) +
         nad_lcm::rsu_info::_computeHash(&cp) +
         nad_lcm::key_point_info::_computeHash(&cp) +
         nad_lcm::route_line_point::_computeHash(&cp) +
         nad_lcm::light_info::_computeHash(&cp) +
         nad_lcm::limspeed_info::_computeHash(&cp) +
         nad_lcm::block_info::_computeHash(&cp) +
         nad_lcm::obstacle_info::_computeHash(&cp) +
         nad_lcm::platoon_info::_computeHash(&cp) +
         nad_lcm::co_obu_info::_computeHash(&cp) +
         nad_lcm::ne_info::_computeHash(&cp) +
         nad_lcm::qos_info::_computeHash(&cp) +
         nad_lcm::route_planning::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
